model:
  _target_: models.space.model.SPACE
  name: space

  # The number of slots is G*G+K and must be set at runtime because OmegaConf doesn't support operators.
  num_slots: null


  fg_params:

    # Grid size. There will be G*G slots
    G: 8  # 4

    # Foreground likelihood sigma
    fg_sigma: 0.15

    glimpse_size: 32

    # Encoded image feature channels
    img_enc_dim_fg: 128

    # Latent dimensions
    z_pres_dim: 1
    z_depth_dim: 1
    z_where_scale_dim: 2
    z_where_shift_dim: 2
    z_what_dim: 32

    z_scale_std_value: 0.1

  bg_params:

    # Number of background components
    K: 5

    # Background likelihood sigma
    bg_sigma: 0.15

    # Image encoding dimension
    img_enc_dim_bg: 64

    # Latent dimensions
    z_mask_dim: 32
    z_comp_dim: 32

    # These should be the same
    rnn_mask_hidden_dim: 64
    rnn_mask_prior_hidden_dim: 64

    # Hidden layer dim for the network that computes q(z_c|z_m, x)
    predict_comp_hidden_dim: 64