
model:
  _target_: src.models.monet.monet.Monet
  name: monet
  num_slots: 4
  bg_sigma: 0.06
  fg_sigma: 0.1
  num_blocks_unet: 5
  beta_kl: 0.5
  gamma: 0.5
  latent_size: 16
  width: 64
  height: 64
  encoder_params:
    channels: [32, 32, 64, 64]
    kernels: [3, 3, 3, 3]
    strides: [2, 2, 2, 2]
    paddings: [0, 0, 0, 0]
    input_channels: 4
    batchnorms: [false, false, false, false]
    bn_affines: [false, false, false, false]
    activations: relu
    mlp_hidden_size: 256
    mlp_output_size: 32  # latent_size * 2
  decoder_params:
    w_broadcast: 64 + 8
    h_broadcast: 64 + 8
    input_channels: 18  # latent_size + 2
    channels: [32, 32, 64, 64, 4]  # last is 4 channels because rgb (3) + mask (1)
    kernels: [3, 3, 3, 3, 1]
    paddings: [0, 0, 0, 0, 0]
    activations: [relu, relu, relu, relu, null]
    batchnorms: [false, false, false, false, false]
    bn_affines: [false, false, false, false, false]